[line_break]
disabled = true

[cmd_duration]
disabled = true

[username]
style_user = "yellow bold"
style_root = "red bold"
format = "($style)"
disabled = false
show_always = true

[hostname]
format =  "[$hostname](bold blue) "
disabled = false
